development:
  adapter: postgresql
  username: sinatra
  password: 12121915
  host: localhost
  database: todo

production:
  adapter: postgresql
  username: sinatra
  password: 12121915
  host: localhost
  database: todo_production
